# Generated by Django 3.1 on 2023-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=100, null=True, unique=True)),
                ('long', models.CharField(max_length=10000, unique=True)),
            ],
        ),
    ]
